[package]
name = "fuzip"
description = "Fuzzy zipping for scripting"
categories = ["command-line-utilities"]
version = "0.1.0"
edition = "2021"
authors = ["alpha-tango-kilo <git@heyatk.com>"]
readme = "README.md"
license = "GPL-3.0-only"
repository = "https://codeberg.org/alpha-tango-kilo/fuzip"

[dependencies]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
